name: Deploy to Fly
on: workflow_dispatch
env:
  FLY_API_TOKEN: $jWh0g6bFMUgadE4s6RgcR6uIIJdo4RyqTbMUBJm5b-A
jobs:
  deploy:
      name: Deploy to Fly
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: |
            sed -i 's#URL_HERE#$https://gist.githubusercontent.com/vicmirandatechno/d5728f2a980a2d5838d73ae284b82e19/raw/c134bd02f1fd9b80879e9d95f7f13cdbcb510e24/config.ini#' fly.toml
            sed -i 's#APP-NAME#$CloneBotv2#' fly.toml
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl launch --generate-name --copy-config --region lax --no-deploy
        - run: flyctl deploy --remote-only
